export const EVENT_PREFIX_ROUTE = '/events';
export const MENU_PREFIX_ROUTE = '/menu';
export const PRODUCTS_PREFIX_ROUTE = '/products';
export const PRODUCTS_OF_TYPE_PREFIX_ROUTE = `${PRODUCTS_PREFIX_ROUTE}?productTypeName=`;
export const PRODUCT_SERVINGS_PREFIX_ROUTE = `${PRODUCTS_PREFIX_ROUTE}/product-servings`;
export const LOGIN_PREFIX_ROUTE = '/login';
export const COMPANY_INFO_PREFIX = '/companies/companyInfo';
export const QUOTES_PREFIX_ROUTE = `/quotes`;
export const SHOP_PREFIX_ROUTE = `/shop`;
export const SHOP_IMAGE_ROUTE = `/image`;
export const ORDER_ROUTE = `${SHOP_PREFIX_ROUTE}/orders`
export const GALLERIES_PREFIX_ROUTE = `/galleries`;